[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    Content-Security-Policy-Report-Only = '''
      default-src 'none';
      script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com;
      connect-src 'self' https://www.google-analytics.com https://*.google-analytics.com https://stats.g.doubleclick.net;
      img-src 'self' https://www.google-analytics.com https://www.googletagmanager.com;
      style-src 'self' 'unsafe-inline';
      manifest-src 'self';
      base-uri 'self';
      form-action 'self';
    '''
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
